// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARd6f8YCUf7YQPM8Zxz4HIYDO11POIxeU',
    appId: '1:680165136338:web:d0a7953d2a8055076e9a0b',
    messagingSenderId: '680165136338',
    projectId: 'neuro-shop',
    authDomain: 'neuro-shop.firebaseapp.com',
    storageBucket: 'neuro-shop.firebasestorage.app',
    measurementId: 'G-RVDCLJ0MBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURzBZksMzeyCd5XT6BL1cDT6-bcQb09s',
    appId: '1:680165136338:android:620102890b31e3486e9a0b',
    messagingSenderId: '680165136338',
    projectId: 'neuro-shop',
    storageBucket: 'neuro-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJacDWJNipdZvcmWwej6D-x-ZzzzI7zk',
    appId: '1:680165136338:ios:f7207e0c65e00d916e9a0b',
    messagingSenderId: '680165136338',
    projectId: 'neuro-shop',
    storageBucket: 'neuro-shop.firebasestorage.app',
    iosBundleId: 'com.nhrepon.neuroShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJacDWJNipdZvcmWwej6D-x-ZzzzI7zk',
    appId: '1:680165136338:ios:f7207e0c65e00d916e9a0b',
    messagingSenderId: '680165136338',
    projectId: 'neuro-shop',
    storageBucket: 'neuro-shop.firebasestorage.app',
    iosBundleId: 'com.nhrepon.neuroShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARd6f8YCUf7YQPM8Zxz4HIYDO11POIxeU',
    appId: '1:680165136338:web:2e7a7953e89a64516e9a0b',
    messagingSenderId: '680165136338',
    projectId: 'neuro-shop',
    authDomain: 'neuro-shop.firebaseapp.com',
    storageBucket: 'neuro-shop.firebasestorage.app',
    measurementId: 'G-N9DKHFYV31',
  );

}